[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.gd",
  "php82Extensions.dom",
  "php82Extensions.xml",
  "php82Extensions.mbstring",
  "php82Extensions.zip",
  "nodejs_22"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"